/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fab1d6ae-aa98-4fb8-a1e5-c650d68f7558",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_fWMqoNUhd",
    "aws_user_pools_web_client_id": "f25755apkpiv7hgnad7n8j8bn",
    "oauth": {},
    "aws_cognito_login_mechanisms": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "pecan-street-data-csv-bucket175351-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
